//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practos3._11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Products
    {
        public int Order_Product { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> products_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
